package com.dataforge.generators.internal;

import com.dataforge.core.DataForgeContext;
import com.dataforge.generators.spi.DataGenerator;
import com.dataforge.model.FieldConfig;
import java.security.SecureRandom;
import java.util.Arrays;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 二维码生成器
 *
 * <p>支持生成各种类型的二维码内容，包括文本、URL、WiFi配置、 联系人信息、短信、邮件等，用于移动应用、营销活动、 信息分享等场景。
 *
 * <p>支持的参数：
 *
 * <ul>
 *   <li>content_type: 内容类型 (TEXT|URL|WIFI|CONTACT|SMS|EMAIL|PHONE|LOCATION|APP) 默认: TEXT
 *   <li>format: 输出格式 (CONTENT|JSON|VCARD|MECARD) 默认: CONTENT
 *   <li>text: 自定义文本内容
 *   <li>url: 自定义URL
 *   <li>wifi_ssid: WiFi网络名称
 *   <li>wifi_password: WiFi密码
 *   <li>wifi_security: WiFi安全类型 (WPA|WEP|NONE) 默认: WPA
 *   <li>contact_name: 联系人姓名
 *   <li>contact_phone: 联系人电话
 *   <li>contact_email: 联系人邮箱
 *   <li>sms_number: 短信号码
 *   <li>sms_message: 短信内容
 *   <li>email_to: 邮件收件人
 *   <li>email_subject: 邮件主题
 *   <li>email_body: 邮件内容
 *   <li>location_lat: 位置纬度
 *   <li>location_lng: 位置经度
 *   <li>app_store: 应用商店 (GOOGLE_PLAY|APP_STORE|CUSTOM) 默认: GOOGLE_PLAY
 *   <li>app_package: 应用包名
 * </ul>
 *
 * @author DataForge Team
 * @since 1.0.0
 */
public class QRCodeGenerator extends BaseGenerator implements DataGenerator<String, FieldConfig> {

  private static final Logger logger = LoggerFactory.getLogger(QRCodeGenerator.class);
  private static final SecureRandom random = new SecureRandom();

  // 内容类型枚举
  public enum ContentType {
    TEXT("纯文本"),
    URL("网址链接"),
    WIFI("WiFi配置"),
    CONTACT("联系人信息"),
    SMS("短信"),
    EMAIL("邮件"),
    PHONE("电话"),
    LOCATION("地理位置"),
    APP("应用下载");

    private final String description;

    ContentType(String description) {
      this.description = description;
    }

    public String getDescription() {
      return description;
    }
  }

  // 输出格式枚举
  public enum OutputFormat {
    CONTENT("原始内容"),
    JSON("JSON格式"),
    VCARD("vCard格式"),
    MECARD("MeCard格式");

    private final String description;

    OutputFormat(String description) {
      this.description = description;
    }

    public String getDescription() {
      return description;
    }
  }

  // 常见网站URL
  private static final List<String> COMMON_URLS =
      Arrays.asList(
          "https://www.google.com",
          "https://www.github.com",
          "https://www.stackoverflow.com",
          "https://www.wikipedia.org",
          "https://www.youtube.com",
          "https://www.amazon.com",
          "https://www.facebook.com",
          "https://www.twitter.com",
          "https://www.linkedin.com",
          "https://www.instagram.com");

  // 常见WiFi网络名称
  private static final List<String> COMMON_WIFI_SSIDS =
      Arrays.asList(
          "Home_WiFi",
          "Office_Network",
          "Guest_Network",
          "MyRouter",
          "WiFi_2.4G",
          "WiFi_5G",
          "TP-Link_Default",
          "Netgear_Home",
          "Linksys_Network",
          "ASUS_Router");

  // 示例文本内容
  private static final List<String> SAMPLE_TEXTS =
      Arrays.asList(
          "Welcome to DataForge!",
          "Scan this QR code for more information",
          "Generated by DataForge QR Code Generator",
          "Hello World from QR Code",
          "Visit our website for updates",
          "Contact us for support",
          "Follow us on social media",
          "Download our mobile app",
          "Join our community",
          "Thank you for using our service");

  @Override
  public String getType() {
    return "qr_code";
  }

  @Override
  public Class<FieldConfig> getConfigClass() {
    return FieldConfig.class;
  }

  @Override
  public String generate(FieldConfig config, DataForgeContext context) {
    try {
      // 获取内容类型
      String contentTypeStr = getStringParam(config, "content_type", "TEXT");
      ContentType contentType = parseContentType(contentTypeStr);

      // 获取输出格式
      String formatStr = getStringParam(config, "format", "CONTENT");
      OutputFormat format = parseOutputFormat(formatStr);

      // 生成二维码内容
      String content = generateQRContent(contentType, config, context);

      // 格式化输出
      return formatQRContent(content, format, contentType);

    } catch (Exception e) {
      logger.error("Failed to generate QR code content", e);
      return "Generated by DataForge QR Code Generator";
    }
  }

  /** 解析内容类型 */
  private ContentType parseContentType(String contentTypeStr) {
    try {
      return ContentType.valueOf(contentTypeStr.toUpperCase());
    } catch (IllegalArgumentException e) {
      logger.warn("Invalid content type: {}, using TEXT as default", contentTypeStr);
      return ContentType.TEXT;
    }
  }

  /** 解析输出格式 */
  private OutputFormat parseOutputFormat(String formatStr) {
    try {
      return OutputFormat.valueOf(formatStr.toUpperCase());
    } catch (IllegalArgumentException e) {
      logger.warn("Invalid output format: {}, using CONTENT as default", formatStr);
      return OutputFormat.CONTENT;
    }
  }

  /** 生成二维码内容 */
  private String generateQRContent(
      ContentType contentType, FieldConfig config, DataForgeContext context) {
    switch (contentType) {
      case TEXT:
        return generateTextContent(config);
      case URL:
        return generateUrlContent(config);
      case WIFI:
        return generateWifiContent(config);
      case CONTACT:
        return generateContactContent(config, context);
      case SMS:
        return generateSmsContent(config);
      case EMAIL:
        return generateEmailContent(config);
      case PHONE:
        return generatePhoneContent(config);
      case LOCATION:
        return generateLocationContent(config);
      case APP:
        return generateAppContent(config);
      default:
        return generateTextContent(config);
    }
  }

  /** 生成文本内容 */
  private String generateTextContent(FieldConfig config) {
    String customText = getStringParam(config, "text", null);
    if (customText != null) {
      return customText;
    }
    return SAMPLE_TEXTS.get(random.nextInt(SAMPLE_TEXTS.size()));
  }

  /** 生成URL内容 */
  private String generateUrlContent(FieldConfig config) {
    String customUrl = getStringParam(config, "url", null);
    if (customUrl != null) {
      return customUrl;
    }
    return COMMON_URLS.get(random.nextInt(COMMON_URLS.size()));
  }

  /** 生成WiFi配置内容 */
  private String generateWifiContent(FieldConfig config) {
    String ssid = getStringParam(config, "wifi_ssid", null);
    if (ssid == null) {
      ssid = COMMON_WIFI_SSIDS.get(random.nextInt(COMMON_WIFI_SSIDS.size()));
    }

    String password = getStringParam(config, "wifi_password", generateWifiPassword());
    String security = getStringParam(config, "wifi_security", "WPA");

    return String.format("WIFI:T:%s;S:%s;P:%s;H:false;;", security, ssid, password);
  }

  /** 生成联系人信息内容 */
  private String generateContactContent(FieldConfig config, DataForgeContext context) {
    String name = getStringParam(config, "contact_name", null);
    String phone = getStringParam(config, "contact_phone", null);
    String email = getStringParam(config, "contact_email", null);

    // 尝试从上下文获取相关信息
    if (name == null) {
      name = context.get("generated_name", String.class).orElse(generateRandomName());
    }
    if (phone == null) {
      phone = context.get("generated_phone", String.class).orElse(generateRandomPhone());
    }
    if (email == null) {
      email = context.get("generated_email", String.class).orElse(generateRandomEmail());
    }

    return String.format(
        "BEGIN:VCARD\nVERSION:3.0\nFN:%s\nTEL:%s\nEMAIL:%s\nEND:VCARD", name, phone, email);
  }

  /** 生成短信内容 */
  private String generateSmsContent(FieldConfig config) {
    String number = getStringParam(config, "sms_number", generateRandomPhone());
    String message = getStringParam(config, "sms_message", "Hello from DataForge!");

    return String.format("SMSTO:%s:%s", number, message);
  }

  /** 生成邮件内容 */
  private String generateEmailContent(FieldConfig config) {
    String to = getStringParam(config, "email_to", "contact@example.com");
    String subject = getStringParam(config, "email_subject", "Hello from DataForge");
    String body =
        getStringParam(config, "email_body", "This is a test email generated by DataForge.");

    return String.format("mailto:%s?subject=%s&body=%s", to, encodeUrl(subject), encodeUrl(body));
  }

  /** 生成电话内容 */
  private String generatePhoneContent(FieldConfig config) {
    String phone = getStringParam(config, "contact_phone", generateRandomPhone());
    return "tel:" + phone;
  }

  /** 生成地理位置内容 */
  private String generateLocationContent(FieldConfig config) {
    String lat = getStringParam(config, "location_lat", null);
    String lng = getStringParam(config, "location_lng", null);

    if (lat == null) {
      lat = String.format("%.6f", 39.9042 + (random.nextDouble() - 0.5) * 0.1); // 北京附近
    }
    if (lng == null) {
      lng = String.format("%.6f", 116.4074 + (random.nextDouble() - 0.5) * 0.1);
    }

    return String.format("geo:%s,%s", lat, lng);
  }

  /** 生成应用下载内容 */
  private String generateAppContent(FieldConfig config) {
    String appStore = getStringParam(config, "app_store", "GOOGLE_PLAY");
    String packageName = getStringParam(config, "app_package", "com.example.app");

    switch (appStore.toUpperCase()) {
      case "GOOGLE_PLAY":
        return "https://play.google.com/store/apps/details?id=" + packageName;
      case "APP_STORE":
        return "https://apps.apple.com/app/id" + generateRandomAppId();
      case "CUSTOM":
        return getStringParam(config, "url", "https://example.com/download");
      default:
        return "https://play.google.com/store/apps/details?id=" + packageName;
    }
  }

  /** 格式化二维码内容 */
  private String formatQRContent(String content, OutputFormat format, ContentType contentType) {
    switch (format) {
      case CONTENT:
        return content;
      case JSON:
        return formatAsJson(content, contentType);
      case VCARD:
        return formatAsVCard(content, contentType);
      case MECARD:
        return formatAsMeCard(content, contentType);
      default:
        return content;
    }
  }

  /** 格式化为JSON格式 */
  private String formatAsJson(String content, ContentType contentType) {
    StringBuilder json = new StringBuilder("{");
    json.append("\"type\":\"").append(contentType.name().toLowerCase()).append("\",");
    json.append("\"content\":\"").append(escapeJson(content)).append("\",");
    json.append("\"description\":\"").append(contentType.getDescription()).append("\"");
    json.append("}");
    return json.toString();
  }

  /** 格式化为vCard格式 */
  private String formatAsVCard(String content, ContentType contentType) {
    if (contentType == ContentType.CONTACT && content.startsWith("BEGIN:VCARD")) {
      return content;
    }

    // 为其他类型创建简单的vCard
    return String.format("BEGIN:VCARD\nVERSION:3.0\nNOTE:%s\nEND:VCARD", content);
  }

  /** 格式化为MeCard格式 */
  private String formatAsMeCard(String content, ContentType contentType) {
    if (contentType == ContentType.CONTACT) {
      return "MECARD:N:Generated Contact;TEL:"
          + generateRandomPhone()
          + ";EMAIL:"
          + generateRandomEmail()
          + ";;";
    }

    return "MECARD:N:DataForge;NOTE:" + content + ";;";
  }

  /** 生成WiFi密码 */
  private String generateWifiPassword() {
    String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    StringBuilder password = new StringBuilder();
    int length = 8 + random.nextInt(8); // 8-15位密码

    for (int i = 0; i < length; i++) {
      password.append(chars.charAt(random.nextInt(chars.length())));
    }

    return password.toString();
  }

  /** 生成随机姓名 */
  private String generateRandomName() {
    String[] firstNames = {"John", "Jane", "Mike", "Sarah", "David", "Lisa", "Tom", "Anna"};
    String[] lastNames = {
      "Smith", "Johnson", "Brown", "Davis", "Wilson", "Miller", "Taylor", "Anderson"
    };

    return firstNames[random.nextInt(firstNames.length)]
        + " "
        + lastNames[random.nextInt(lastNames.length)];
  }

  /** 生成随机电话号码 */
  private String generateRandomPhone() {
    return String.format(
        "+1%03d%03d%04d",
        200 + random.nextInt(800), 200 + random.nextInt(800), 1000 + random.nextInt(9000));
  }

  /** 生成随机邮箱 */
  private String generateRandomEmail() {
    String[] domains = {"gmail.com", "yahoo.com", "hotmail.com", "outlook.com", "example.com"};
    String username = "user" + (1000 + random.nextInt(9000));
    String domain = domains[random.nextInt(domains.length)];

    return username + "@" + domain;
  }

  /** 生成随机应用ID */
  private String generateRandomAppId() {
    return String.valueOf(100000000 + random.nextInt(900000000));
  }

  /** URL编码 */
  private String encodeUrl(String text) {
    return text.replace(" ", "%20").replace("&", "%26").replace("=", "%3D");
  }

  /** JSON转义 */
  private String escapeJson(String text) {
    return text.replace("\"", "\\\"")
        .replace("\\", "\\\\")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t");
  }
}
